

name: CI

on:
  
  push:
  workflow_dispatch:
  pull_request:

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:
    
      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer 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" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/devops-fundamentos-v6/status-check/statuses/beb6d3dda53928f9b0d792059d08e5a28c2833c2 \
          -d '{"state":"success","target_url":"https://example.com/build/status","description":"Security checkov IaC","context":"continuous-integration/checkov"}'
